/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedSolicitacoesIndexRouteImport } from './routes/_authenticated/solicitacoes/index'
import { Route as AuthenticatedIndicadoresIndexRouteImport } from './routes/_authenticated/indicadores/index'
import { Route as AuthenticatedAuditoriaIndexRouteImport } from './routes/_authenticated/auditoria/index'
import { Route as AuthenticatedAprovacoesIndexRouteImport } from './routes/_authenticated/aprovacoes/index'
import { Route as AuthenticatedSolicitacoesNovaRouteImport } from './routes/_authenticated/solicitacoes/nova'
import { Route as AuthenticatedSolicitacoesIdRouteImport } from './routes/_authenticated/solicitacoes/$id'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedAdministracaoRegrasRouteImport } from './routes/_authenticated/administracao/regras'
import { Route as AuthenticatedAdministracaoIntegracoesRouteImport } from './routes/_authenticated/administracao/integracoes'
import { Route as AuthenticatedSolicitacoesIdCorrigirRouteImport } from './routes/_authenticated/solicitacoes/$id_.corrigir'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSolicitacoesIndexRoute =
  AuthenticatedSolicitacoesIndexRouteImport.update({
    id: '/solicitacoes/',
    path: '/solicitacoes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIndicadoresIndexRoute =
  AuthenticatedIndicadoresIndexRouteImport.update({
    id: '/indicadores/',
    path: '/indicadores/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAuditoriaIndexRoute =
  AuthenticatedAuditoriaIndexRouteImport.update({
    id: '/auditoria/',
    path: '/auditoria/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAprovacoesIndexRoute =
  AuthenticatedAprovacoesIndexRouteImport.update({
    id: '/aprovacoes/',
    path: '/aprovacoes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSolicitacoesNovaRoute =
  AuthenticatedSolicitacoesNovaRouteImport.update({
    id: '/solicitacoes/nova',
    path: '/solicitacoes/nova',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSolicitacoesIdRoute =
  AuthenticatedSolicitacoesIdRouteImport.update({
    id: '/solicitacoes/$id',
    path: '/solicitacoes/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdministracaoRegrasRoute =
  AuthenticatedAdministracaoRegrasRouteImport.update({
    id: '/administracao/regras',
    path: '/administracao/regras',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdministracaoIntegracoesRoute =
  AuthenticatedAdministracaoIntegracoesRouteImport.update({
    id: '/administracao/integracoes',
    path: '/administracao/integracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSolicitacoesIdCorrigirRoute =
  AuthenticatedSolicitacoesIdCorrigirRouteImport.update({
    id: '/solicitacoes/$id_/corrigir',
    path: '/solicitacoes/$id/corrigir',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/administracao/integracoes': typeof AuthenticatedAdministracaoIntegracoesRoute
  '/administracao/regras': typeof AuthenticatedAdministracaoRegrasRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/solicitacoes/$id': typeof AuthenticatedSolicitacoesIdRoute
  '/solicitacoes/nova': typeof AuthenticatedSolicitacoesNovaRoute
  '/aprovacoes/': typeof AuthenticatedAprovacoesIndexRoute
  '/auditoria/': typeof AuthenticatedAuditoriaIndexRoute
  '/indicadores/': typeof AuthenticatedIndicadoresIndexRoute
  '/solicitacoes/': typeof AuthenticatedSolicitacoesIndexRoute
  '/solicitacoes/$id/corrigir': typeof AuthenticatedSolicitacoesIdCorrigirRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/administracao/integracoes': typeof AuthenticatedAdministracaoIntegracoesRoute
  '/administracao/regras': typeof AuthenticatedAdministracaoRegrasRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/solicitacoes/$id': typeof AuthenticatedSolicitacoesIdRoute
  '/solicitacoes/nova': typeof AuthenticatedSolicitacoesNovaRoute
  '/aprovacoes': typeof AuthenticatedAprovacoesIndexRoute
  '/auditoria': typeof AuthenticatedAuditoriaIndexRoute
  '/indicadores': typeof AuthenticatedIndicadoresIndexRoute
  '/solicitacoes': typeof AuthenticatedSolicitacoesIndexRoute
  '/solicitacoes/$id/corrigir': typeof AuthenticatedSolicitacoesIdCorrigirRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/administracao/integracoes': typeof AuthenticatedAdministracaoIntegracoesRoute
  '/_authenticated/administracao/regras': typeof AuthenticatedAdministracaoRegrasRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/solicitacoes/$id': typeof AuthenticatedSolicitacoesIdRoute
  '/_authenticated/solicitacoes/nova': typeof AuthenticatedSolicitacoesNovaRoute
  '/_authenticated/aprovacoes/': typeof AuthenticatedAprovacoesIndexRoute
  '/_authenticated/auditoria/': typeof AuthenticatedAuditoriaIndexRoute
  '/_authenticated/indicadores/': typeof AuthenticatedIndicadoresIndexRoute
  '/_authenticated/solicitacoes/': typeof AuthenticatedSolicitacoesIndexRoute
  '/_authenticated/solicitacoes/$id_/corrigir': typeof AuthenticatedSolicitacoesIdCorrigirRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/administracao/integracoes'
    | '/administracao/regras'
    | '/errors/$error'
    | '/solicitacoes/$id'
    | '/solicitacoes/nova'
    | '/aprovacoes/'
    | '/auditoria/'
    | '/indicadores/'
    | '/solicitacoes/'
    | '/solicitacoes/$id/corrigir'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/administracao/integracoes'
    | '/administracao/regras'
    | '/errors/$error'
    | '/solicitacoes/$id'
    | '/solicitacoes/nova'
    | '/aprovacoes'
    | '/auditoria'
    | '/indicadores'
    | '/solicitacoes'
    | '/solicitacoes/$id/corrigir'
  id:
    | '__root__'
    | '/_authenticated'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/administracao/integracoes'
    | '/_authenticated/administracao/regras'
    | '/_authenticated/errors/$error'
    | '/_authenticated/solicitacoes/$id'
    | '/_authenticated/solicitacoes/nova'
    | '/_authenticated/aprovacoes/'
    | '/_authenticated/auditoria/'
    | '/_authenticated/indicadores/'
    | '/_authenticated/solicitacoes/'
    | '/_authenticated/solicitacoes/$id_/corrigir'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/solicitacoes/': {
      id: '/_authenticated/solicitacoes/'
      path: '/solicitacoes'
      fullPath: '/solicitacoes/'
      preLoaderRoute: typeof AuthenticatedSolicitacoesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/indicadores/': {
      id: '/_authenticated/indicadores/'
      path: '/indicadores'
      fullPath: '/indicadores/'
      preLoaderRoute: typeof AuthenticatedIndicadoresIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/auditoria/': {
      id: '/_authenticated/auditoria/'
      path: '/auditoria'
      fullPath: '/auditoria/'
      preLoaderRoute: typeof AuthenticatedAuditoriaIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/aprovacoes/': {
      id: '/_authenticated/aprovacoes/'
      path: '/aprovacoes'
      fullPath: '/aprovacoes/'
      preLoaderRoute: typeof AuthenticatedAprovacoesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/solicitacoes/nova': {
      id: '/_authenticated/solicitacoes/nova'
      path: '/solicitacoes/nova'
      fullPath: '/solicitacoes/nova'
      preLoaderRoute: typeof AuthenticatedSolicitacoesNovaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/solicitacoes/$id': {
      id: '/_authenticated/solicitacoes/$id'
      path: '/solicitacoes/$id'
      fullPath: '/solicitacoes/$id'
      preLoaderRoute: typeof AuthenticatedSolicitacoesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/administracao/regras': {
      id: '/_authenticated/administracao/regras'
      path: '/administracao/regras'
      fullPath: '/administracao/regras'
      preLoaderRoute: typeof AuthenticatedAdministracaoRegrasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/administracao/integracoes': {
      id: '/_authenticated/administracao/integracoes'
      path: '/administracao/integracoes'
      fullPath: '/administracao/integracoes'
      preLoaderRoute: typeof AuthenticatedAdministracaoIntegracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/solicitacoes/$id_/corrigir': {
      id: '/_authenticated/solicitacoes/$id_/corrigir'
      path: '/solicitacoes/$id/corrigir'
      fullPath: '/solicitacoes/$id/corrigir'
      preLoaderRoute: typeof AuthenticatedSolicitacoesIdCorrigirRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdministracaoIntegracoesRoute: typeof AuthenticatedAdministracaoIntegracoesRoute
  AuthenticatedAdministracaoRegrasRoute: typeof AuthenticatedAdministracaoRegrasRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedSolicitacoesIdRoute: typeof AuthenticatedSolicitacoesIdRoute
  AuthenticatedSolicitacoesNovaRoute: typeof AuthenticatedSolicitacoesNovaRoute
  AuthenticatedAprovacoesIndexRoute: typeof AuthenticatedAprovacoesIndexRoute
  AuthenticatedAuditoriaIndexRoute: typeof AuthenticatedAuditoriaIndexRoute
  AuthenticatedIndicadoresIndexRoute: typeof AuthenticatedIndicadoresIndexRoute
  AuthenticatedSolicitacoesIndexRoute: typeof AuthenticatedSolicitacoesIndexRoute
  AuthenticatedSolicitacoesIdCorrigirRoute: typeof AuthenticatedSolicitacoesIdCorrigirRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdministracaoIntegracoesRoute:
    AuthenticatedAdministracaoIntegracoesRoute,
  AuthenticatedAdministracaoRegrasRoute: AuthenticatedAdministracaoRegrasRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedSolicitacoesIdRoute: AuthenticatedSolicitacoesIdRoute,
  AuthenticatedSolicitacoesNovaRoute: AuthenticatedSolicitacoesNovaRoute,
  AuthenticatedAprovacoesIndexRoute: AuthenticatedAprovacoesIndexRoute,
  AuthenticatedAuditoriaIndexRoute: AuthenticatedAuditoriaIndexRoute,
  AuthenticatedIndicadoresIndexRoute: AuthenticatedIndicadoresIndexRoute,
  AuthenticatedSolicitacoesIndexRoute: AuthenticatedSolicitacoesIndexRoute,
  AuthenticatedSolicitacoesIdCorrigirRoute:
    AuthenticatedSolicitacoesIdCorrigirRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
